#pragma once

#define WHITE_PIECE 'W'
#define BLACK_PIECE 'B'
#define EMPTY_PIECE '_'
#define OUTSIDE_PIECE '+'


#define EXIT_CMD "EXIT"
#define LOAD_GAME_CMD "LOAD_GAME_BOARD"
#define PRINT_BOARD_CMD "PRINT_GAME_BOARD"
#define DO_MOVE_CMD "DO_MOVE"

#define GAME_STATE_PROGRESS "in_progress"
//...

#define BOARD_STATUS_OK "BOARD_STATE_OK"
#define BOARD_STATUS_WHITE_COUNT "WRONG_WHITE_PAWNS_NUMBER"
#define BOARD_STATUS_BLACK_COUNT "WRONG_BLACK_PAWNS_NUMBER"
#define BOARD_STATUS_SIZE "WRONG_BOARD_ROW_LENGTH"

#define MOVE_STATUS_OK ""
#define MOVE_STATUS_INDEX(x) "BAD_MOVE_#x_IS_WRONG_INDEX"
#define MOVE_STATUS_DIR "UNKNOWN_MOVE_DIRECTION"
#define MOVE_STATUS_BAD_START(x) "BAD_MOVE_#X_IS_WRONG_STARTING_FIELD"
#define MOVE_STATUS_BAD_DEST(x) "BAD_MOVE_#X_IS_WRONG_DESTINATION_FIELD"
#define MOVE_STATUS_ROW "BAD_MOVE_ROW_IS_FULL"