#pragma once

#define WHITE_PIECE 'W'
#define BLACK_PIECE 'B'
#define EMPTY_PIECE '_'
#define OUTSIDE_PIECE '+'


#define EXIT_CMD "EXIT"
#define LOAD_GAME_CMD "LOAD_GAME_BOARD"
#define PRINT_BOARD_CMD "PRINT_GAME_BOARD"
#define DO_MOVE_CMD "DO_MOVE"
#define GAME_STATE_CMD "PRINT_GAME_STATE"

#define GAME_STATE_PROGRESS "in_progress"
#define GAME_STATE_BAD_MOVE "bad_move"
#define GAME_STATE_WHITE_WIN "white_win"
#define GAME_STATE_BLACK_WIN "black_win"

#define MOVE_CHOICE_WRONG_COLOR "WRONG_COLOR_OF_CHOSEN_ROW"
#define MOVE_CHOICE_WRONG_INDEX "WRONG_INDEX_OF_CHOSEN_ROW"

#define BOARD_STATUS_EMPTY "EMPTY_BOARD"
#define BOARD_STATUS_OK "BOARD_STATE_OK"
#define BOARD_STATUS_WHITE_COUNT "WRONG_WHITE_PAWNS_NUMBER"
#define BOARD_STATUS_BLACK_COUNT "WRONG_BLACK_PAWNS_NUMBER"
#define BOARD_STATUS_SIZE "WRONG_BOARD_ROW_LENGTH"
#define BOARD_STATUS_CHAIN_SINGLE "_ROW_OF_LENGTH_K"
#define BOARD_STATUS_CHAINS_MULTIPLE "_ROWS_OF_LENGTH_K"
#define BOARD_STATUS_ERROR "ERROR_FOUND_"

#define MOVE_STATUS_OK "MOVE_COMMITTED"
#define MOVE_STATUS_BAD_PREFIX "BAD_MOVE_"
#define MOVE_STATUS_INDEX "_IS_WRONG_INDEX"
#define MOVE_STATUS_DIR "UNKNOWN_MOVE_DIRECTION"
#define MOVE_STATUS_BAD_START "_IS_WRONG_STARTING_FIELD"
#define MOVE_STATUS_BAD_DEST "_IS_WRONG_DESTINATION_FIELD"
#define MOVE_STATUS_ROW "BAD_MOVE_ROW_IS_FULL"